### ISSUE TITLE
Instructions to change bot icon in the Telegram client

### ISSUE THREAD

**Issue by facundobatista** [facundobatista/recordium#20]
Add in the README step by steps to download an image from bit.ly/recordium (where the logo is stored) and how to tell botfather to use that image

**Comment by lorenariveira** [comment]
I don't know how to edit the README but these instructions work properly. BTW the link to the logo doesn't work.

```
After creating new bot you can type the command `/setuserpic`. It asks you to select which of your bots you want to edit and after the selection it asks you to send the picture.

If you want to use Recordium logo you'll find it here bit.ly/recordium
```

**Comment by facundobatista** [comment]
Thanks! I used this info to include instructions in the README!
