### ISSUE TITLE
If no messages to show, don't open the messages window

### ISSUE THREAD

**Issue by facundobatista** [facundobatista/recordium#4]
Just open an alert dialog saying something like "No messages to show."

**Comment by marian-vignau** [comment]
ok

**Comment by facundobatista** [comment]
I was wrong. If there are no messages to show, the "0 new messages" should just not be clickable!

It's silly to let the user to click on something, just to tell her "nothing for you!".

So, the first line of the systray icon menu should still be "0 new messages" but greyed-out, or inactive, or something, so the user can not click it and understands she can not click on it.

**Comment by marian-vignau** [comment]
Done
